sensor:
  - platform: rest
    unique_id: sensor.avenet42_co2
    name: avenet42 co2
    device_class: carbon_dioxide
    unit_of_measurement: "ppm"
    resource: "http://192.168.0.129/status.json"
    value_template: "{{ value_json.co2_ppm }}"
  - platform: rest
    unique_id: sensor.avenet42_humidity
    name: avenet42 Humidity
    device_class: humidity
    unit_of_measurement: "%"
    resource: "http://192.168.0.129/status.json"
    value_template: "{{ value_json.relative_humidity }}"
  - platform: rest
    unique_id: sensor.avenet42_temperature
    name: avenet42 Temperature
    device_class: temperature
    unit_of_measurement: "°C"
    resource: "http://192.168.0.129/status.json"
    value_template: "{{ value_json.temp_celsius }}"