rest:
  - resource: "http://192.168.0.129/status.json"
    scan_interval: 30
    sensor:
      - name: "avenet42 CO2"
        unique_id: sensor.avenet42_co2
        value_template: "{{ value_json.co2_ppm }}"
        device_class: carbon_dioxide
        unit_of_measurement: "ppm"

      - name: "avenet42 Humidity"
        unique_id: sensor.avenet42_humidity
        value_template: "{{ value_json.relative_humidity }}"
        device_class: humidity
        unit_of_measurement: "%"

      - name: "avenet42 Temperature"
        unique_id: sensor.avenet42_temperature
        value_template: "{{ value_json.temp_celsius }}"
        device_class: temperature
        unit_of_measurement: "°C"
